export const JS_BRIDGE_MESSAGE_IPC_CHANNEL = 'qiaomc@JS_BRIDGE_MESSAGE_IPC_CHANNEL';
export const JS_BRIDGE_MESSAGE_EXT_CHANNEL = 'qiaomc@JS_BRIDGE_MESSAGE_EXT_CHANNEL';
export const JS_BRIDGE_MESSAGE_EXT_PING = 'qiaomc@JS_BRIDGE_MESSAGE_EXT_PING';
export const JS_BRIDGE_MESSAGE_DIRECTION = {
  'HOST_TO_INPAGE': 'qiaomc@JS_BRIDGE_MESSAGE_DIRECTION-HOST_TO_INPAGE',
  'INPAGE_TO_HOST': 'qiaomc@JS_BRIDGE_MESSAGE_DIRECTION-INPAGE_TO_HOST',
};
export const EXT_PORT_OFFSCREEN_TO_BG = 'qiaomc@EXT_PORT_OFFSCREEN_TO_BG';
export const EXT_PORT_CS_TO_BG = 'qiaomc@EXT_PORT_CS_TO_BG';
export const EXT_PORT_UI_TO_BG = 'qiaomc@EXT_PORT_UI_TO_BG';
export const DEBUG_LOGGER_STORAGE_KEY = '$$QIAOMC_DEBUG_LOGGER';
export const WALLET_INFO_LOACAL_KEY = 'qiaomc_wallet_info_local_key'
export const WALLET_INFO_LOACAL_KEY_V5 = "qiaomc_wallet_info_local_key_v5";
export const QIAOMC_REQUEST_TO_ALL_CS = '$$QIAOMC_REQUEST_TO_ALL_CS';
