name: test-example-web-build

on:
  pull_request:
    branches: [main,master]

jobs:
  test_build_web:
    runs-on: ubuntu-latest
    env:
      TEST_ENDPOINT: dapp-example.qiaomctest.com
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install Dependency
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'skipped yarn install at workspace root'

      - name: Build Target
        run: |
          yarn example-build
